export const siteConfig = {
  name: 'AetherMine',
  fullName: 'AetherMine Minecraft RPG Server',
  serverIp: 'mc.aethermines.com',
  serverIpPe: 'mc.aethermines.com:24932',
  pePort: '24932',
  versionSupport: '1.20.4+',
  recommendedVersion: '1.20.4 – 1.20.6',
  websiteUrl: 'https://aethermines.com',
  bannerUrl: '/banner.png',
  logoUrl: '/logo.png',
  author: 'AetherMine Studio',
  social: {
    discord: 'https://discord.gg/mvRcGjDHVm',
    facebook: 'https://facebook.com/aethermine',
  },
  navLinks: [
    { name: 'Tính Năng', href: '/#features' },
    { name: 'Rank', href: '/#ranks' },
    { name: 'Trang Bị', href: '/#gears' },
    { name: 'Kinh Tế', href: '/#economy' },
    { name: 'Blog', href: '/blog' },
    { name: 'FAQ', href: '/#faq' },
    { name: 'Cộng Đồng', href: '/#community' },
  ],
};
